### ISSUE TITLE
[07.13 ~ 07.20] 이우림 Todo

### ISSUE THREAD

**Issue by woorimlee** [DEVMasterBros/Mermes#1]
- [x] 바로형 시퀀스 다이어그램 작성하라고 쪼기
- [x] 자연어 처리를 위한 라이브러리 선정 및 사용

**Comment by gimbaro** [comment]
Mermes Architecture - 7/21 (바로)
Data Parser Test Version - 7/22(바로)
자연어 처리를 위한 라이브러리 선정 및 사용 -7/22 (우림)

**Comment by woorimlee** [comment]
konlpy 사용
